### ISSUE TITLE
Pull-Main.sh missing [Bug]

### ISSUE THREAD

**Issue by kingso** [skills/deploy-to-azure#38]
**Describe the bug**
This script is missing and fails the action run.

**Comment by markpatterson27** [comment]
For context, this is needed for the `2-setup-azure-environments.yml`, `3-spinup-environment.yml` and `4-deploy-to-staging-environment.yml` workflows.

https://github.com/skills/continuous-delivery-azure/blob/045a9a6c934b71601f9e97a4081d15d7e1cef426/.github/workflows/2-setup-azure-environment.yml#L80-L84

`pull-main.sh` doesn't exist in the repo.

**Comment by gsacavdm** [comment]
The fix is to change that to `./.github/script/initialize-repository.sh`

**Comment by markpatterson27** [comment]
@gsacavdm I don't think `./.github/script/initialize-repository.sh` is the right script to run. `initialize-repository.sh` is written for linking branch histories after repo creation. It does this by merging `main` into all branches.

Looking at the context for `pull-main.sh`, it looks like it is meant to pull and checkout `main` so that the next action can update the steps in the README. (Otherwise the steps won't get updated on `main` but on the feature branch instead.) `initialize-repository.sh` doesn't do this.

**Comment by rffontenelle** [comment]
Fixed in #51 with pull-main.sh renamed to initialize-repository.sh, and given exec permission. See:

https://github.com/skills/deploy-to-azure/blob/main/.github/workflows/2-setup-azure-environment.yml#L108-L114

**Comment by hectorsector** [comment]
Thanks for following up, @rffontenelle
